### ISSUE TITLE
Service int_monei.http.rest returns error

### ISSUE THREAD

**Issue by federicogiampietro** [MONEI/MONEI-Salesforce#1]
Hello,

the service int_monei.http.rest upon first call always returns the following message
SSLHandshakeException:com.demandware.beehive.core.internal.ssl.WrappedCertificateException:
sun.security.validator.ValidatorException: PKIX path validation failed
java.security.cert.CertPathValidatorException: validity check failed

this happens both on sandbox and development environment, the latter with a valid SSL certificate. Seems like the API endpoint is protected not only by the authorization header but with a certificate check as well.

A mocked up API call with Postman works ok only if the option to check the SSL certificate validity is turned off

**Comment by jimmyn** [comment]
Please provide the API call with Postman so we can investigate the issue

**Comment by federicogiampietro** [comment]
I'll provide partially obscured screenshots since the call contains sensitive info


![Schermata 2023-05-16 alle 10 29 20](https://github.com/MONEI/MONEI-Salesforce/assets/92781198/1354e930-57b4-4ec5-be82-a9b64c182bcd)
![Schermata 2023-05-16 alle 10 30 14](https://github.com/MONEI/MONEI-Salesforce/assets/92781198/2962374f-ee21-48ef-8b10-a2abf348efc5)

**Comment by jimmyn** [comment]
The endpoint should be **https://api.monei.com/v1**

**Comment by federicogiampietro** [comment]
What???

the service credentials i've got it configured for being "https://api.monei.com/v1" but the code adds the endpoint to the service url. Obviously it has to be this way because MONEI has a list of available endpoints (https://docs.monei.com/api/) all starts with "https://api.monei.com/v1/" but when making an API call the correct endpoint has to be selected for the call itself.

The url i've used in postman and shared here is the exact url the code is calling when trying to open the MONEI popup (creating the payment in MONEI)


anyway, even by following your suggestion and calling a non-existing MONEI endpoint, i get the same response


can you send me an example of a call that you can make through postman?

![Schermata 2023-05-16 alle 11 13 36](https://github.com/MONEI/MONEI-Salesforce/assets/92781198/2571c99b-6c57-4dcd-938b-1e2fc0d360f1)

**Comment by jimmyn** [comment]
You can find the postman collection here - https://postman.monei.com/

<img width="1369" alt="image" src="https://github.com/MONEI/MONEI-Salesforce/assets/5391775/13204a27-ef3d-441a-b8e7-2b257f8a920b">

```
curl --location 'https://api.monei.com/v1/payments' \
--header 'Authorization: <API_KEY>' \
--header 'Content-Type: application/json' \
--data '{
    "amount": 110,
    "currency": "EUR",
    "orderId": "12345678",
    "callbackUrl": "https://example.com/checkout/callback",
    "completeUrl": "https://example.com/checkout/complete"
}'
```

**Comment by federicogiampietro** [comment]
follows screenshot of call debugging in CC

![Schermata 2023-05-16 alle 12 42 47](https://github.com/MONEI/MONEI-Salesforce/assets/92781198/7c9db778-9f06-4d16-9cd7-9c76a28efaea)
![Schermata 2023-05-16 alle 12 42 55](https://github.com/MONEI/MONEI-Salesforce/assets/92781198/5ca5e1b5-3dfc-4590-9a26-d36c3884e911)

**Comment by federicogiampietro** [comment]
Tried the GET payment endpoint, same result.

Be advised that no other API endpoints to other domains return this error, both on CCloud and Postman

**Comment by federicogiampietro** [comment]
didn't noticed the endpoint was .NET instead of .COM . it works with the .com endpoint


please update the XML meta definition of the service versioned with the cartridge because it points to the .net domain


![Schermata 2023-05-16 alle 12 55 02](https://github.com/MONEI/MONEI-Salesforce/assets/92781198/8d31fc6d-6a0a-414a-bd83-bc9d86f623c9)

**Comment by jimmyn** [comment]
This is weird, I get the same error in postman if I enable the certificate validation, but the certificate is valid and not expired

```
 ~ openssl s_client -servername api.monei.com -connect api.monei.com:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Feb 28 00:00:00 2023 GMT
notAfter=Jan 23 23:59:59 2024 GMT
```

**Comment by federicogiampietro** [comment]
with the validation enabled, the api.monei.com domain is not returning the error at all
i only got the issue (both on postman and CCloud) by using the api.monei.net domain which indeed is the wrong domain but it's the one that the versioned xmls in the cartridge contain

i think we can close the issue if you could update the xmls it would avoid the issue to happen again to others :)

**Comment by federicogiampietro** [comment]
there was an open issue for postman regarding ssl certificates generated by let's encrypt that was regarding the error you're mentioning (certificate valid but not recognized) that was fixed at some point https://github.com/postmanlabs/postman-app-support/issues/10338 

maybe you could try update the postman app if that's the one you're using

anyway as stated in the previous message my issue was related the `.net` domain usage instead of the `.com`

**Comment by jimmyn** [comment]
Fixed, thank you for pointing that out.
